# ===========================
# Application
# ===========================
spring.application.name=notification-service
server.port=8090

# ===========================
# RabbitMQ (Docker)
# ===========================
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}
spring.rabbitmq.virtual-host=/
spring.rabbitmq.ssl.enabled=false

# ===========================
# MindFocus RabbitMQ Config
# ===========================
mindfocus.rabbitmq.exchange=mindfocus.event.exchange

mindfocus.rabbitmq.queues.notification-events=mindfocus.notification.queue
mindfocus.rabbitmq.routing-keys.notification=habito.criado

# ===========================
# Logging
# ===========================
logging.level.org.springframework=INFO
logging.level.com.example=DEBUG
logging.level.org.springframework.amqp=DEBUG
